version: '3'

services:
  dotnet:
    build: .
    ports:
      - "15000:5000"
    volumes:
      - "./project:/project"
    tty: true
    # command: dotnet run --urls http://0.0.0.0:5000 --project ./Server/
